language: node_js
sudo: required
dist: trusty
node_js: "8"
env: CXX=g++-4.8
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: g++-4.8
before_script: npm install -g gulp
script:
  - gulp prep
before_deploy:
  - openssl aes-256-cbc -K $encrypted_85fecf66b314_key -iv $encrypted_85fecf66b314_iv -in mew.gpg.enc -out mew.gpg -d
  - mkdir deploy
  - gpg --allow-secret-key-import --import mew.gpg
  - gulp clean
  - gulp travisZip
  - |
    for f in deploy/*; do
      gpg --output $f.sig --detach-sig $f
    done
deploy:
  provider: releases
  api_key:
    secure: NYFD7bSlHoGA/UahbPs8r8vKf5CAz78e4HFJyXsFGQN4oC1xc6TCl578WzUbahBCfgjeKOMKoG7eOQYPoPkgoX8Q62jDdPAIuC90dGpaPeYjoKZcESAI18kZHHsX3QWzUVxG83qjv4XD3ReoBdFzHqsR3FnPh3j1AdMCrIOHHuBViAARWPK+FvXyxRyiUYrAPr/Pemv8A8hroOm2KPhDVFfHBC9tOtoOeqiuvULlwoSnt9VWe4Uj80B+JB0wPmYbWs/K8jrq8iRfJTRMGdIaAulnxPGvG7Yl+0Zq8wCqz8ogZu5E5YxSxGT/2aU6xmBRThCsXR+bz0dHAou6t12GfJXo2EIBkSFXBk2lCu4mCrwFMIHOHjt0EACHTxdK8v564ec2Wa6Tfk3y+QGyhocSCBkyLwGLFFXflWWqwEYoAcZEc+A9AzolLboIT99XKaB/ofBNa7m7LL72Lg9crGMVcDIM/ilN87l3Osiy80rCXyJAkoOVeIhhd2f2wNybN0f0AMtHj8O1dio2IOqnRMmx4yEEbeIvLG30AiAkw0OI/DpAj0V1ZPWJh1a1KgUlSgvVKO+POI9bwZ3mKe81eiE/fhizNT4rEgN4qhyfXe0aV04Ox47Y2wxpxU+5MSltvRhvt3Ml/Q4RL1Ti4j0ewRQasD85lqO49wzGkpsjqJme6BQ=
  file_glob: true
  file: deploy/*
  skip_cleanup: true
  on:
    repo: kvhnuke/etherwallet
    branch: mercury
    tags: true
notifications:
  slack:
    secure: qiRVkvr+ErtjPrZ3BYXsisYCqS8alTsx9L3bkxkRdst7hkFxc/QzxPFxOHFTdxXUiispTfxXabAV31JEpLzUx25cPRLkR/gnHk4yUtQ4HlwjsSxb+4Gi99WvuNmLq22uD3e+O1//JCiGAF/hcnglx9ifWfFK/cgVwjIVuqxyHj7MiZSEke388odH8GMDF/MdpClQQ8c4MMaM6hnQqt5yocgXhnATxZyzJbJ+ljD6n64MGG7IYZ60vCmWTkUDwIwwhIAG/bYWjU3s8f+0kxdZpPQcWwGIJ9GNaVrcbvORKrHEQ/RUUmpv5WzsiUIahJflrQSWr4zciQU3AZyXpp4z+MMM+uBh0cg8GIk1lXXwYQfDLAeD/JR/NSgGiDzwAFv73dEwsBAf1lG43knuowfmt6fZoXMrC+rztptX36hdJ/XFyaWEQnfnqBjeNJ8OfmlyL++8ojgDbuioBdsnHKFQPG3Bt6rxPCL/C98ZAotxWOmjr4wfdQIxewiEo2ghjgwoLW9KJBFtGg+IxQC3ymHKRPaujK1y0X5tTIgBeydEd63fQU/n3jrbwJaZ2ExKmE2Ixl7YfWJ7TybA/h+ZGaoueiugVhy/ENuqg3xffQtXI7bZVgNYbY4MM9JanBZyOu8BccddVZYnZAOBYAiRhsNH5XsARLF3mftP6zw3XNfYwRA=
